version: "3.8"

services:

  frontend-app:
    container_name: frontend-app
    restart: 'unless-stopped'
    build: ./frontend
    ports:
      - 80:80
    networks:
      - backend_net

  admin-app:
    container_name: admin-app
    restart: 'unless-stopped'
    build: ./admin
    ports:
      - 81:80
    networks:
      - backend_net

  db:
    container_name: mysql-database
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: cinemaDB
    volumes:
      - ./docker-config/sql/cinema.sql:/docker-entrypoint-initdb.d/cinema.sql
      - mysql_data:/var/lib/mysql #Mount volume để không mất dữ liệu khi restart
    restart: always
    networks:
      - backend_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  restful-app:
    container_name: backend-app
    build: ./backend
    restart: 'unless-stopped'
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 9595:9595
    environment:
      #- SPRING_PROFILES_ACTIVE=local  #de no chay file app.properties local
      - DB_HOST=db
      - DB_NAME=cinemaDB
      - DB_USER=root
      - DB_PASSWORD=123456789
      - TZ=Asia/Ho_Chi_Minh
    networks:
      - backend_net

  phpmyadmin:
    container_name: php-my-admin-app
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 32346:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: CC6tjBh6mkJ8h8PXU7cg8zUx4E6ABFrMQ44EaxU59yfTvYyzWS
    networks:
      - backend_net

networks:
  backend_net:
    driver: bridge

volumes:
  mysql_data: # Định nghĩa volume bền vững
